Added apache commons pool2 dependency
A NoClassDefFoundError would get thrown without this dependency. Relocation appears to not work very well either, so it has been excluded for now